"use client";

import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import MaterialIcon from "@/components/MaterialIcon";
import { MarkdownContent } from "@/components/MarkdownContent";

type PresetDraft = {
    title: string;
    description: string;
    type: "AGENT" | "SCRAPE";
    category: string;
    icon: string;
    time_estimate: string;
    target_url: string;
    configuration: string;
    expected_output: string;
    readme: string;
};

export default function NewPresetPage() {
    const router = useRouter();
    const inputRef = useRef<HTMLInputElement>(null);
    const iconInputRef = useRef<HTMLInputElement>(null);
    const [draft, setDraft] = useState<PresetDraft | null>(null);
    const [fileName, setFileName] = useState("");
    const [note, setNote] = useState("");
    const [error, setError] = useState("");
    const [generating, setGenerating] = useState(false);
    const [publishing, setPublishing] = useState(false);
    const [iconMode, setIconMode] = useState<"upload" | "favicon">("upload");

    const useFavicon = () => {
        if (!draft) return;
        try {
            const domain = new URL(draft.target_url).hostname;
            setDraft({ ...draft, icon: domain });
        } catch {
            setDraft({ ...draft, icon: "" });
        }
        setIconMode("favicon");
    };

    const uploadIcon = (file: File) => {
        if (!draft) return;
        const reader = new FileReader();
        reader.onload = event => {
            const image = new Image();
            image.onload = () => {
                const canvas = document.createElement("canvas");
                canvas.width = 96;
                canvas.height = 96;
                const context = canvas.getContext("2d");
                if (!context) return;
                const size = Math.min(image.width, image.height);
                context.drawImage(image, (image.width - size) / 2, (image.height - size) / 2, size, size, 0, 0, 96, 96);
                setDraft(current => current ? { ...current, icon: canvas.toDataURL("image/webp", 0.9) } : current);
                setIconMode("upload");
            };
            image.src = event.target?.result as string;
        };
        reader.readAsDataURL(file);
    };

    const generateFromFile = async (file: File) => {
        setError("");
        setNote("");
        setDraft(null);

        if (!file.name.toLowerCase().endsWith(".json") && file.type !== "application/json") {
            setError("Choose a JSON file exported from Figranium.");
            return;
        }
        if (file.size > 2 * 1024 * 1024) {
            setError("The JSON file must be smaller than 2 MB.");
            return;
        }

        setFileName(file.name);
        setGenerating(true);
        try {
            const configuration = await file.text();
            JSON.parse(configuration);
            const response = await fetch("/api/presets/generate", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ configuration }),
            });
            const data = await response.json();
            if (response.status === 401) {
                router.push("/auth/signin");
                return;
            }
            if (!response.ok) throw new Error(data.error || "Could not prepare this template.");
            setDraft(data.draft);
            setNote(data.note || "Deterministic fields were extracted and the marketplace copy was generated by AI.");
        } catch (cause) {
            setError(cause instanceof SyntaxError ? "The selected file is not valid JSON." : cause instanceof Error ? cause.message : "Could not prepare this template.");
        } finally {
            setGenerating(false);
            if (inputRef.current) inputRef.current.value = "";
        }
    };

    const publish = async () => {
        if (!draft) return;
        if (!draft.icon.trim()) {
            setError("Choose an uploaded icon or favicon before publishing.");
            return;
        }
        setPublishing(true);
        setError("");
        try {
            const response = await fetch("/api/presets", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify(draft),
            });
            const data = await response.json();
            if (response.status === 401) {
                router.push("/auth/signin");
                return;
            }
            if (!response.ok) throw new Error(data.error || "Could not publish this template.");
            router.push("/");
            router.refresh();
        } catch (cause) {
            setError(cause instanceof Error ? cause.message : "Could not publish this template.");
        } finally {
            setPublishing(false);
        }
    };

    return (
        <div className="flex min-h-[80vh] flex-col items-center px-5 py-12 sm:px-8 lg:px-10 lg:py-16">
            <div className="w-full max-w-[960px]">
                <p className="page-kicker mb-3">Workspace / Publish</p>
                <h1 className="text-3xl font-bold tracking-[-0.045em] sm:text-4xl">Publish from JSON</h1>
                <p className="mt-3 max-w-2xl text-[14px] leading-6 text-white/42">
                    Upload one Figranium task. The app extracts everything it can reliably determine, then AI writes the description, category, and README. You can optionally add an expected-output example before publishing.
                </p>

                {error && (
                    <div className="mt-7 flex items-center gap-2 rounded-[11px] border border-red-500/25 bg-red-500/10 p-3 text-sm text-red-300">
                        <MaterialIcon name="error" className="text-lg" /> {error}
                    </div>
                )}

                <div className="product-panel mt-8 p-5 sm:p-7">
                    <button
                        type="button"
                        disabled={generating || publishing}
                        onClick={() => inputRef.current?.click()}
                        onDragOver={event => event.preventDefault()}
                        onDrop={event => {
                            event.preventDefault();
                            const file = event.dataTransfer.files[0];
                            if (file) void generateFromFile(file);
                        }}
                        className="flex min-h-56 w-full flex-col items-center justify-center rounded-[14px] border border-dashed border-white/[0.14] bg-white/[0.018] px-6 text-center transition hover:border-white/30 hover:bg-white/[0.035] disabled:cursor-wait disabled:opacity-60"
                    >
                        <span className="mb-5 flex h-12 w-12 items-center justify-center rounded-[12px] border border-white/[0.1] bg-white/[0.04]">
                            <MaterialIcon name={generating ? "progress_activity" : "upload_file"} className={`text-2xl ${generating ? "animate-spin" : ""}`} />
                        </span>
                        <span className="text-[15px] font-semibold">{generating ? "Reading the task and writing its page…" : "Drop your template JSON here"}</span>
                        <span className="mt-2 text-xs text-white/35">{fileName && generating ? fileName : "or click to choose a file · 2 MB max"}</span>
                    </button>
                    <input
                        ref={inputRef}
                        type="file"
                        accept=".json,application/json"
                        className="hidden"
                        onChange={event => {
                            const file = event.target.files?.[0];
                            if (file) void generateFromFile(file);
                        }}
                    />
                </div>

                {draft && (
                    <div className="mt-8 space-y-6">
                        <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
                            <div>
                                <p className="page-kicker mb-2">Ready to publish</p>
                                <h2 className="text-2xl font-bold tracking-[-0.035em]">Generated marketplace page</h2>
                                <p className="mt-2 text-xs text-emerald-300/75">{note}</p>
                            </div>
                            <button
                                type="button"
                                onClick={() => void publish()}
                                disabled={publishing}
                                className="inline-flex h-11 items-center justify-center gap-2 rounded-[10px] bg-white px-5 text-[13px] font-semibold text-black transition hover:bg-white/85 disabled:cursor-wait disabled:opacity-60"
                            >
                                <MaterialIcon name={publishing ? "progress_activity" : "publish"} className={publishing ? "animate-spin" : ""} />
                                {publishing ? "Publishing…" : "Publish template"}
                            </button>
                        </div>

                        <div className="product-panel p-6 sm:p-8">
                            <div className="flex flex-col gap-5 sm:flex-row sm:items-start">
                                <div className="flex h-14 w-14 shrink-0 items-center justify-center overflow-hidden rounded-[12px] border border-white/[0.09] bg-white/[0.03]">
                                    {draft.icon.startsWith("data:image/") ? <img src={draft.icon} className="h-full w-full object-cover" alt="Template icon" /> : draft.icon.includes(".") ? <img src={`https://www.google.com/s2/favicons?domain=${draft.icon}&sz=64`} className="h-9 w-9 object-contain" alt="" /> : <MaterialIcon name="image" className="text-3xl text-white/30" />}
                                </div>
                                <div className="min-w-0 flex-1">
                                    <div className="flex flex-wrap items-center gap-2">
                                        <h3 className="text-xl font-bold tracking-[-0.025em]">{draft.title}</h3>
                                        <span className="rounded border border-white/[0.09] bg-white/[0.03] px-2 py-0.5 text-[10px] text-white/55">{draft.type}</span>
                                        <span className="rounded border border-white/[0.09] bg-white/[0.03] px-2 py-0.5 text-[10px] text-white/55">{draft.category}</span>
                                    </div>
                                    <p className="mt-3 text-[14px] leading-6 text-white/52">{draft.description}</p>
                                    <div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-xs text-white/34">
                                        <span>{draft.target_url || "No target URL"}</span><span>{fileName}</span>
                                    </div>
                                </div>
                            </div>

                            <div className="mt-6 border-t border-white/[0.08] pt-6">
                                <div className="mb-3 flex items-center justify-between">
                                    <p className="text-[10px] font-bold uppercase tracking-[0.14em] text-white/38">Template icon</p>
                                    <span className="text-[10px] uppercase tracking-[0.12em] text-white/25">Required</span>
                                </div>
                                <div className="grid gap-3 sm:grid-cols-2">
                                    <button
                                        type="button"
                                        onClick={() => iconInputRef.current?.click()}
                                        className={`flex min-h-11 items-center justify-center gap-2 rounded-[10px] border px-4 text-xs transition ${iconMode === "upload" ? "border-white/25 bg-white/[0.07] text-white" : "border-white/[0.09] text-white/45 hover:text-white"}`}
                                    >
                                        <MaterialIcon name="upload" className="text-lg" /> Upload image
                                    </button>
                                    <button
                                        type="button"
                                        onClick={useFavicon}
                                        className={`flex min-h-11 items-center justify-center gap-2 rounded-[10px] border px-4 text-xs transition ${iconMode === "favicon" ? "border-white/25 bg-white/[0.07] text-white" : "border-white/[0.09] text-white/45 hover:text-white"}`}
                                    >
                                        <MaterialIcon name="language" className="text-lg" /> Use site favicon
                                    </button>
                                </div>
                                <input
                                    ref={iconInputRef}
                                    type="file"
                                    accept="image/*"
                                    className="hidden"
                                    onChange={event => {
                                        const file = event.target.files?.[0];
                                        if (file) uploadIcon(file);
                                        event.target.value = "";
                                    }}
                                />
                                <p className="mt-3 text-[11px] text-white/28">Uploaded images are cropped to a 96×96 square. Favicon uses the task’s target domain.</p>
                            </div>
                        </div>

                        <div className="grid gap-6 lg:grid-cols-2">
                            <section className="product-panel p-6">
                                <div className="mb-4 flex items-center justify-between gap-3">
                                    <h3 className="flex items-center gap-2 text-sm font-semibold uppercase tracking-[0.08em] text-white/60"><MaterialIcon name="output" className="text-lg" /> Expected output</h3>
                                    <span className="text-[10px] uppercase tracking-[0.12em] text-white/25">Optional</span>
                                </div>
                                <textarea
                                    rows={9}
                                    value={draft.expected_output}
                                    onChange={event => setDraft({ ...draft, expected_output: event.target.value })}
                                    placeholder="Paste an example of what this template produces…"
                                    className="w-full resize-y rounded-[10px] border border-white/[0.09] bg-black/40 px-3 py-2 font-mono text-xs leading-6 text-white outline-none transition placeholder:text-white/25 focus:border-white/25"
                                />
                            </section>
                            <section className="product-panel p-6">
                                <h3 className="mb-4 flex items-center gap-2 text-sm font-semibold uppercase tracking-[0.08em] text-white/60"><MaterialIcon name="description" className="text-lg" /> README</h3>
                                <MarkdownContent className="max-h-[420px] overflow-auto">{draft.readme}</MarkdownContent>
                            </section>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
}
